version: '3.9'

services:
    postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        PGDATA: "/var/lib/postgresql/data/pgdata"
      ports:
        - "${POSTGRES_PORTS}:${POSTGRES_PORTS}"
      volumes:
        - ./storage/pgdata:/var/lib/postgresql/data/pgdata
        - ./storage/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      container_name: ${POSTGRES_CONTAINER_NAME}
    nats-streaming:
      image: nats-streaming:latest
      command: ["-cid", "${NATS_CLUSTER}"]
      ports:
        - "${NATS_PORTS}:${NATS_PORTS}"
      depends_on:
        - postgres
      container_name: ${NATS_CONTAINER_NAME}
    server:
      build:
        dockerfile: Dockerfile
        context: .
      image: my_server_image
      ports:
        - "${SERVER_PORTS}:${SERVER_PORTS}"
      environment:
        CONFIG_PATH: "./config/local.yaml"
      volumes:
        - ./logs/:/app/logs/
      depends_on:
        - nats-streaming
      container_name: ${SERVER_CONTAINER_NAME}
