version: '3.9'

services:
    postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        PGDATA: "/var/lib/postgresql/data/pgdata"
      ports:
        - "${POSTGRES_PORTS}:5432"
      volumes:
        - ./storage/pgdata:/var/lib/postgresql/data/pgdata
        - ./storage/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      container_name: ${POSTGRES_CONTAINER_NAME}