# Поскольку проект учебный, было принято решение позволить
# определять пользователя и пароль в конфигурационном файле,
# для более удобного использования.

postgres:
  host: "localhost"
  port: "5100"
  user: "user"
  password: "user"
  dbname: "wb_storage"
  containername: "postgres_container"
nats_streaming:
  host: "localhost"
  port: "4200"
  client_id: "1"
  cluster_id: "show_orders_cluster"
  subscribe_subject: "streaming_orders"
  containername: "nats-streaming_container"
server:
  host: "localhost"
  port: "8081"
  timeout: 4s
  idle_timeout: 60s